### PR TITLE
Updated 'package-lock.json'.

### LINKED ISSUE #10: Update package-lock.json for NPM 8
```sh
nvm use 8
npm install
```

causes `package-lock.json` to be updated for new syntax.  We might as well use any new improvements to the `package-lock.json` file, as it (should be) backwards compatible.

### PR DESCRIPTION
**Pull request by CodeLenny**
Closes #10

### CODE REVIEW

**Review by stevehoover — APPROVED** [review]
I'll keep this in mind for my next CI.

**Comment by CodeLenny** [comment]
@stevehoover I also just got a notification (from GitHub) that there's a known vulnerability in one of the libraries used.  I think it's just used for documentation generation (so not a big deal), but shall I update the dependencies while I'm making changes?

**Comment by stevehoover** [comment]
Seems best.

**Comment by CodeLenny** [comment]
Thanks, will do!

**Pull request merged**
